### ISSUE TITLE
Kanban setup

### ISSUE THREAD

**Issue by Amrhub** [Amrhub/space-travelers-hub#21]
We are a team of 2 members, here is a [link for kanban](https://github.com/Amrhub/space-travelers-hub/projects/2)

**Comment by omar-labana** [comment]
Hi team, 

Excellent work so far! 👌
You have implemented almost all the required features. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
- [x] There should be a total of `17` cards in the project board after removing all the cards with `Team3` (I can only see 13), Please, double-check your board.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
_N/A_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Amrhub** [comment]
Hi Code Reviewer, 
We updated the link to the required changes, please check it out

**Comment by Ghiftee** [comment]
## STATUS: APPROVED ♻️♻️
Hi @Amrhub @piero-vic  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://media.giphy.com/media/s2qXK8wAvkHTO/giphy.gif)

Cheers and Happy coding!👏👏👏
